### ISSUE TITLE
OSCPortIn removeListener

### ISSUE THREAD

**Issue by TidensBarn** [hoijui/JavaOSC#39]
There's no way to remove a Listener from OSCPortIn once it has been added.

**Comment by hoijui** [comment]
Thanks for the report! :-)
There already is a way on the `develop` branch, so it will be fixed with the next realease, or you can build the `develop` branch yoruself, or use the snapshot release.
First fixed in fb67c6c1da347c7d40d0ee5db105530d2d107e8f, though the functionality was later changed again.

**Comment by hoijui** [comment]
I just released a new snapshot version (`com.illposed.osc:javaosc-core:0.5-SNAPSHOT`) to sonatype. It should be available in a few minutes.
