### ISSUE TITLE
API for the OSC 1.1 required argument type "Impulse"

### ISSUE THREAD

**Issue by hoijui** [hoijui/JavaOSC#9]
i wonder if any of you have a different/better/more elegant solution to implement it then how it is done in this commit: https://github.com/hoijui/JavaOSC/commit/e81f95a94aad40404ecd9b9048d3b593927a258b

with this implementation, we would have to use it like this:

```
OSCMessage msg = new OSCMessage("/my/address");
msg.addArgument(OSCImpulse.INSTANCE);
```

**Comment by daveyarwood** [comment]
I'm late to the party, but I happened to just be looking at this code, so here is my 2¢ while it's fresh:

I think the idea of having an overload of `addArgument` that takes an instance of a distinct class `OSCImpulse` makes perfect sense.

I think providing a `OSCImpulse.INSTANCE` (and encouraging its use) is also totally reasonable, although I would think `msg.addArgument(new OSCImpulse())` would be fine too. I think it makes sense to provide `OSCImpulse.INSTANCE` so that people have options.

**Comment by hoijui** [comment]
thank you for the input!
I guess I chose the `OSCImpulse.INSTANCE` way for performance reasons, as it prevents people from creating a new instance of the class for each impulse they are sending. Though I agree that `msg.addArgument(new OSCImpulse())` looks better.
